
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace MotionCore.Gameplay.Configs
{
/// <summary>
/// 角色生成记录
/// </summary>
public sealed partial class CharacterSpawn : Luban.BeanBase
{
    public CharacterSpawn(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CharacterId = _buf.ReadInt();
        CharacterId_Ref = null;
        PosX = _buf.ReadFloat();
        PosY = _buf.ReadFloat();
        PosZ = _buf.ReadFloat();
        Yaw = _buf.ReadFloat();
    }

    public static CharacterSpawn DeserializeCharacterSpawn(ByteBuf _buf)
    {
        return new CharacterSpawn(_buf);
    }

    /// <summary>
    /// 生成记录 ID（3xxx 段）
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色原型 ID
    /// </summary>
    public readonly int CharacterId;
    public CharacterRow CharacterId_Ref;
    /// <summary>
    /// 世界坐标 X
    /// </summary>
    public readonly float PosX;
    /// <summary>
    /// 世界坐标 Y
    /// </summary>
    public readonly float PosY;
    /// <summary>
    /// 世界坐标 Z
    /// </summary>
    public readonly float PosZ;
    /// <summary>
    /// 绕 Y 轴角度
    /// </summary>
    public readonly float Yaw;
   
    public const int __ID__ = -656103950;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CharacterId_Ref = tables.TbCharacter.GetOrDefault(CharacterId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "characterId:" + CharacterId + ","
        + "posX:" + PosX + ","
        + "posY:" + PosY + ","
        + "posZ:" + PosZ + ","
        + "yaw:" + Yaw + ","
        + "}";
    }
}
}

