
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace MotionCore.Gameplay.Configs
{
public partial class Tables
{
    /// <summary>
    /// 角色原型表
    /// </summary>
    public TbCharacter TbCharacter {get; }
    /// <summary>
    /// 角色基础数值表
    /// </summary>
    public TbCharacterStat TbCharacterStat {get; }
    /// <summary>
    /// 角色生成表
    /// </summary>
    public TbCharacterSpawn TbCharacterSpawn {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCharacter = new TbCharacter(loader("tbcharacter"));
        TbCharacterStat = new TbCharacterStat(loader("tbcharacterstat"));
        TbCharacterSpawn = new TbCharacterSpawn(loader("tbcharacterspawn"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacter.ResolveRef(this);
        TbCharacterStat.ResolveRef(this);
        TbCharacterSpawn.ResolveRef(this);
    }

    public System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.Type, object>> GetAllTables()
    {
        yield return new System.Collections.Generic.KeyValuePair<System.Type, object>(
            typeof(TbCharacter), TbCharacter);
        yield return new System.Collections.Generic.KeyValuePair<System.Type, object>(
            typeof(TbCharacterStat), TbCharacterStat);
        yield return new System.Collections.Generic.KeyValuePair<System.Type, object>(
            typeof(TbCharacterSpawn), TbCharacterSpawn);
    }
}

}

